<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-02T20:49:20 EDT" name="Surefire suite" finished-at="2024-05-02T20:49:29 EDT" duration-ms="8986">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner@e50a6f6]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-05-02T20:49:20 EDT" name="Surefire test" finished-at="2024-05-02T20:49:29 EDT" duration-ms="8986">
      <class name="TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:TestRunner@e50a6f6]" started-at="2024-05-02T20:49:20 EDT" name="setUpClass" finished-at="2024-05-02T20:49:20 EDT" duration-ms="368" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@15eb5ee5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunner@e50a6f6]" started-at="2024-05-02T20:49:20 EDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-05-02T20:49:28 EDT" duration-ms="8039" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Student should be able to login with valid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Student Information - Fail] but found [Student Information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Student Information - Fail] but found [Student Information]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDef.Login_steps.studentShouldBeSuccessfullyLoginButFailingOnPurpose(Login_steps.java:66)
at âœ½.student should be successfully login but failing on purpose(file:///Users/hbhuiyan/Documents/TalentTEK/GitStuff/CucumberOnline3x_March24/src/test/java/features/login.feature:25)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:TestRunner@e50a6f6]" started-at="2024-05-02T20:49:28 EDT" name="tearDownClass" finished-at="2024-05-02T20:49:29 EDT" duration-ms="511" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
